//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BasicAuthScopes = "basicAuth.Scopes"
)

// Defines values for AssetCode.
const (
	AssetCodeBTC AssetCode = "BTC"
	AssetCodeETH AssetCode = "ETH"
)

// Defines values for BalanceAssetCode.
const (
	BalanceAssetCodeBTC BalanceAssetCode = "BTC"
	BalanceAssetCodeETH BalanceAssetCode = "ETH"
	BalanceAssetCodeJPY BalanceAssetCode = "JPY"
)

// Defines values for CreateOrderRequestTimeInForce.
const (
	FAK CreateOrderRequestTimeInForce = "FAK"
	FAS CreateOrderRequestTimeInForce = "FAS"
	FOK CreateOrderRequestTimeInForce = "FOK"
	SOK CreateOrderRequestTimeInForce = "SOK"
)

// Defines values for JobRunStatus.
const (
	JobRunStatusFailed    JobRunStatus = "failed"
	JobRunStatusRunning   JobRunStatus = "running"
	JobRunStatusSkipped   JobRunStatus = "skipped"
	JobRunStatusSucceeded JobRunStatus = "succeeded"
)

// Defines values for JobType.
const (
	DailyTrade     JobType = "daily_trade"
	Manual         JobType = "manual"
	OrderReconcile JobType = "order_reconcile"
	PriceFetch     JobType = "price_fetch"
)

// Defines values for OrderSide.
const (
	Buy  OrderSide = "buy"
	Sell OrderSide = "sell"
)

// Defines values for OrderStatus.
const (
	OrderStatusCancelRequested OrderStatus = "cancel_requested"
	OrderStatusCancelled       OrderStatus = "cancelled"
	OrderStatusExpired         OrderStatus = "expired"
	OrderStatusFailed          OrderStatus = "failed"
	OrderStatusFilled          OrderStatus = "filled"
	OrderStatusOpen            OrderStatus = "open"
	OrderStatusPartiallyFilled OrderStatus = "partially_filled"
	OrderStatusPendingSubmit   OrderStatus = "pending_submit"
	OrderStatusRejected        OrderStatus = "rejected"
)

// Defines values for OrderType.
const (
	OrderTypeLimit OrderType = "limit"
)

// AssetCode defines model for AssetCode.
type AssetCode string

// BalanceAssetCode defines model for BalanceAssetCode.
type BalanceAssetCode string

// CancelOrderResponse defines model for CancelOrderResponse.
type CancelOrderResponse struct {
	OrderId int64       `json:"orderId"`
	Status  OrderStatus `json:"status"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	AssetCode AssetCode `json:"assetCode"`

	// PriceJpy decimal string
	PriceJpy    string                         `json:"priceJpy"`
	RequestedBy *string                        `json:"requestedBy,omitempty"`
	Side        OrderSide                      `json:"side"`
	TimeInForce *CreateOrderRequestTimeInForce `json:"timeInForce,omitempty"`

	// Units decimal string
	Units string `json:"units"`
}

// CreateOrderRequestTimeInForce defines model for CreateOrderRequest.TimeInForce.
type CreateOrderRequestTimeInForce string

// CreateOrderResponse defines model for CreateOrderResponse.
type CreateOrderResponse struct {
	Order Order `json:"order"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ExecutionListResponse defines model for ExecutionListResponse.
type ExecutionListResponse struct {
	Executions []TradeExecution `json:"executions"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	CheckedAt time.Time `json:"checkedAt"`
	Status    string    `json:"status"`
}

// JobRunListResponse defines model for JobRunListResponse.
type JobRunListResponse struct {
	JobRuns []JobRunSummary `json:"jobRuns"`
}

// JobRunStatus defines model for JobRunStatus.
type JobRunStatus string

// JobRunSummary defines model for JobRunSummary.
type JobRunSummary struct {
	ErrorCode    *string      `json:"errorCode,omitempty"`
	ErrorMessage *string      `json:"errorMessage,omitempty"`
	FinishedAt   *time.Time   `json:"finishedAt,omitempty"`
	Id           int64        `json:"id"`
	JobType      JobType      `json:"jobType"`
	ScheduledFor time.Time    `json:"scheduledFor"`
	StartedAt    time.Time    `json:"startedAt"`
	Status       JobRunStatus `json:"status"`
}

// JobType defines model for JobType.
type JobType string

// LatestBalancesResponse defines model for LatestBalancesResponse.
type LatestBalancesResponse struct {
	Balances []SummaryAsset `json:"balances"`
}

// LatestPricesResponse defines model for LatestPricesResponse.
type LatestPricesResponse struct {
	Prices []PriceSnapshot `json:"prices"`
}

// Order defines model for Order.
type Order struct {
	AssetCode       AssetCode          `json:"assetCode"`
	CancelledAt     *time.Time         `json:"cancelledAt,omitempty"`
	ClientOrderId   openapi_types.UUID `json:"clientOrderId"`
	ExchangeOrderId string             `json:"exchangeOrderId"`
	ExpiresAt       *time.Time         `json:"expiresAt,omitempty"`

	// FeeJpy decimal string
	FeeJpy string `json:"feeJpy"`

	// FilledUnits decimal string
	FilledUnits         string     `json:"filledUnits"`
	Id                  int64      `json:"id"`
	IsFeeFree           bool       `json:"isFeeFree"`
	LastStatusCheckedAt *time.Time `json:"lastStatusCheckedAt,omitempty"`
	OrderType           OrderType  `json:"orderType"`

	// OrderedUnits decimal string
	OrderedUnits string    `json:"orderedUnits"`
	PlacedAt     time.Time `json:"placedAt"`

	// PriceJpy decimal string
	PriceJpy string `json:"priceJpy"`

	// RemainingUnits decimal string
	RemainingUnits string      `json:"remainingUnits"`
	Side           OrderSide   `json:"side"`
	Status         OrderStatus `json:"status"`
}

// OrderDetailResponse defines model for OrderDetailResponse.
type OrderDetailResponse struct {
	Events []OrderEvent `json:"events"`
	Order  Order        `json:"order"`
}

// OrderEvent defines model for OrderEvent.
type OrderEvent struct {
	EventAt    time.Time               `json:"eventAt"`
	EventType  string                  `json:"eventType"`
	FromStatus *OrderStatus            `json:"fromStatus,omitempty"`
	Id         int64                   `json:"id"`
	Payload    *map[string]interface{} `json:"payload,omitempty"`
	ToStatus   *OrderStatus            `json:"toStatus,omitempty"`
}

// OrderListResponse defines model for OrderListResponse.
type OrderListResponse struct {
	Orders []Order `json:"orders"`
}

// OrderSide defines model for OrderSide.
type OrderSide string

// OrderStatus defines model for OrderStatus.
type OrderStatus string

// OrderType defines model for OrderType.
type OrderType string

// PriceHistoryResponse defines model for PriceHistoryResponse.
type PriceHistoryResponse struct {
	Prices []PriceSnapshot `json:"prices"`
}

// PriceSnapshot defines model for PriceSnapshot.
type PriceSnapshot struct {
	AssetCode  AssetCode `json:"assetCode"`
	CapturedAt time.Time `json:"capturedAt"`
	Id         int64     `json:"id"`

	// PriceJpy decimal string
	PriceJpy string `json:"priceJpy"`
	Source   string `json:"source"`
}

// SummaryAsset defines model for SummaryAsset.
type SummaryAsset struct {
	AssetCode BalanceAssetCode `json:"assetCode"`

	// AvailableAmount decimal string
	AvailableAmount string `json:"availableAmount"`

	// LockedAmount decimal string
	LockedAmount string `json:"lockedAmount"`
}

// SummaryOrderStats defines model for SummaryOrderStats.
type SummaryOrderStats struct {
	OpenCount                  int32 `json:"openCount"`
	UnresolvedPreviousDayCount int32 `json:"unresolvedPreviousDayCount"`
}

// SummaryWeeklyLimit defines model for SummaryWeeklyLimit.
type SummaryWeeklyLimit struct {
	AssetCode AssetCode `json:"assetCode"`

	// ConsumedUnits decimal string
	ConsumedUnits string `json:"consumedUnits"`

	// LimitUnits decimal string
	LimitUnits string `json:"limitUnits"`

	// RemainingUnits decimal string
	RemainingUnits  string    `json:"remainingUnits"`
	WindowStartedAt time.Time `json:"windowStartedAt"`
}

// SystemSummaryResponse defines model for SystemSummaryResponse.
type SystemSummaryResponse struct {
	Balances      []SummaryAsset       `json:"balances"`
	LatestJobRuns []JobRunSummary      `json:"latestJobRuns"`
	OrderStats    SummaryOrderStats    `json:"orderStats"`
	ServerTime    time.Time            `json:"serverTime"`
	WeeklyLimits  []SummaryWeeklyLimit `json:"weeklyLimits"`
}

// TradeExecution defines model for TradeExecution.
type TradeExecution struct {
	ExchangeExecutionId string    `json:"exchangeExecutionId"`
	ExecutedAt          time.Time `json:"executedAt"`

	// ExecutedUnits decimal string
	ExecutedUnits string `json:"executedUnits"`

	// FeeJpy decimal string
	FeeJpy        string `json:"feeJpy"`
	Id            int64  `json:"id"`
	IsPartialFill bool   `json:"isPartialFill"`
	OrderId       int64  `json:"orderId"`

	// PriceJpy decimal string
	PriceJpy string `json:"priceJpy"`
}

// TriggerJobRequest defines model for TriggerJobRequest.
type TriggerJobRequest struct {
	// Reason 手動実行理由
	Reason *string `json:"reason,omitempty"`

	// RequestedBy 実行主体の識別子
	RequestedBy *string `json:"requestedBy,omitempty"`
}

// TriggerJobResponse defines model for TriggerJobResponse.
type TriggerJobResponse struct {
	JobRunId int64  `json:"jobRunId"`
	Status   string `json:"status"`
}

// AssetCodeRequired defines model for AssetCodeRequired.
type AssetCodeRequired = AssetCode

// BalanceAssetCodeOptional defines model for BalanceAssetCodeOptional.
type BalanceAssetCodeOptional = BalanceAssetCode

// FromAt defines model for FromAt.
type FromAt = time.Time

// JobStatus defines model for JobStatus.
type JobStatus = JobRunStatus

// Limit defines model for Limit.
type Limit = int

// OrderId defines model for OrderId.
type OrderId = int64

// OrderIdOptional defines model for OrderIdOptional.
type OrderIdOptional = int64

// ToAt defines model for ToAt.
type ToAt = time.Time

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// GetLatestBalancesParams defines parameters for GetLatestBalances.
type GetLatestBalancesParams struct {
	AssetCode *BalanceAssetCodeOptional `form:"assetCode,omitempty" json:"assetCode,omitempty"`
}

// ListExecutionsParams defines parameters for ListExecutions.
type ListExecutionsParams struct {
	AssetCode *AssetCode       `form:"assetCode,omitempty" json:"assetCode,omitempty"`
	OrderId   *OrderIdOptional `form:"orderId,omitempty" json:"orderId,omitempty"`
	Limit     *Limit           `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListJobRunsParams defines parameters for ListJobRuns.
type ListJobRunsParams struct {
	JobType *JobType   `form:"jobType,omitempty" json:"jobType,omitempty"`
	Status  *JobStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit   *Limit     `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListOrdersParams defines parameters for ListOrders.
type ListOrdersParams struct {
	AssetCode *AssetCode   `form:"assetCode,omitempty" json:"assetCode,omitempty"`
	Side      *OrderSide   `form:"side,omitempty" json:"side,omitempty"`
	Status    *OrderStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit     *Limit       `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListPriceHistoryParams defines parameters for ListPriceHistory.
type ListPriceHistoryParams struct {
	AssetCode AssetCodeRequired `form:"assetCode" json:"assetCode"`
	From      *FromAt           `form:"from,omitempty" json:"from,omitempty"`
	To        *ToAt             `form:"to,omitempty" json:"to,omitempty"`
	Limit     *Limit            `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetLatestPricesParams defines parameters for GetLatestPrices.
type GetLatestPricesParams struct {
	AssetCode *AssetCode `form:"assetCode,omitempty" json:"assetCode,omitempty"`
}

// TriggerDailyTradeJobJSONRequestBody defines body for TriggerDailyTradeJob for application/json ContentType.
type TriggerDailyTradeJobJSONRequestBody = TriggerJobRequest

// TriggerOrderReconcileJobJSONRequestBody defines body for TriggerOrderReconcileJob for application/json ContentType.
type TriggerOrderReconcileJobJSONRequestBody = TriggerJobRequest

// TriggerPriceFetchJobJSONRequestBody defines body for TriggerPriceFetchJob for application/json ContentType.
type TriggerPriceFetchJobJSONRequestBody = TriggerJobRequest

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 最新残高を取得
	// (GET /api/v1/balances/latest)
	GetLatestBalances(w http.ResponseWriter, r *http.Request, params GetLatestBalancesParams)
	// 約定履歴を取得
	// (GET /api/v1/executions)
	ListExecutions(w http.ResponseWriter, r *http.Request, params ListExecutionsParams)
	// ジョブ実行履歴を取得
	// (GET /api/v1/job-runs)
	ListJobRuns(w http.ResponseWriter, r *http.Request, params ListJobRunsParams)
	// 日次売買ジョブを手動起動
	// (POST /api/v1/job-runs/daily-trade)
	TriggerDailyTradeJob(w http.ResponseWriter, r *http.Request)
	// 注文同期ジョブを手動起動
	// (POST /api/v1/job-runs/order-reconcile)
	TriggerOrderReconcileJob(w http.ResponseWriter, r *http.Request)
	// 価格取得ジョブを手動起動
	// (POST /api/v1/job-runs/price-fetch)
	TriggerPriceFetchJob(w http.ResponseWriter, r *http.Request)
	// 注文一覧を取得
	// (GET /api/v1/orders)
	ListOrders(w http.ResponseWriter, r *http.Request, params ListOrdersParams)
	// 注文を作成
	// (POST /api/v1/orders)
	CreateOrder(w http.ResponseWriter, r *http.Request)
	// 注文詳細を取得
	// (GET /api/v1/orders/{orderId})
	GetOrder(w http.ResponseWriter, r *http.Request, orderId OrderId)
	// 注文を取消
	// (POST /api/v1/orders/{orderId}/cancel)
	CancelOrder(w http.ResponseWriter, r *http.Request, orderId OrderId)
	// 価格履歴を取得
	// (GET /api/v1/prices/history)
	ListPriceHistory(w http.ResponseWriter, r *http.Request, params ListPriceHistoryParams)
	// 最新価格を取得
	// (GET /api/v1/prices/latest)
	GetLatestPrices(w http.ResponseWriter, r *http.Request, params GetLatestPricesParams)
	// ダッシュボード向けのサマリーを取得
	// (GET /api/v1/system/summary)
	GetSystemSummary(w http.ResponseWriter, r *http.Request)
	// ヘルスチェック
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLatestBalances operation middleware
func (siw *ServerInterfaceWrapper) GetLatestBalances(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestBalancesParams

	// ------------- Optional query parameter "assetCode" -------------

	err = runtime.BindQueryParameter("form", true, false, "assetCode", r.URL.Query(), &params.AssetCode)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "assetCode", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLatestBalances(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListExecutions operation middleware
func (siw *ServerInterfaceWrapper) ListExecutions(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExecutionsParams

	// ------------- Optional query parameter "assetCode" -------------

	err = runtime.BindQueryParameter("form", true, false, "assetCode", r.URL.Query(), &params.AssetCode)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "assetCode", Err: err})
		return
	}

	// ------------- Optional query parameter "orderId" -------------

	err = runtime.BindQueryParameter("form", true, false, "orderId", r.URL.Query(), &params.OrderId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListExecutions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListJobRuns operation middleware
func (siw *ServerInterfaceWrapper) ListJobRuns(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListJobRunsParams

	// ------------- Optional query parameter "jobType" -------------

	err = runtime.BindQueryParameter("form", true, false, "jobType", r.URL.Query(), &params.JobType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "jobType", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListJobRuns(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerDailyTradeJob operation middleware
func (siw *ServerInterfaceWrapper) TriggerDailyTradeJob(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerDailyTradeJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerOrderReconcileJob operation middleware
func (siw *ServerInterfaceWrapper) TriggerOrderReconcileJob(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerOrderReconcileJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerPriceFetchJob operation middleware
func (siw *ServerInterfaceWrapper) TriggerPriceFetchJob(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerPriceFetchJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrders operation middleware
func (siw *ServerInterfaceWrapper) ListOrders(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrdersParams

	// ------------- Optional query parameter "assetCode" -------------

	err = runtime.BindQueryParameter("form", true, false, "assetCode", r.URL.Query(), &params.AssetCode)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "assetCode", Err: err})
		return
	}

	// ------------- Optional query parameter "side" -------------

	err = runtime.BindQueryParameter("form", true, false, "side", r.URL.Query(), &params.Side)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "side", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrder(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrder operation middleware
func (siw *ServerInterfaceWrapper) GetOrder(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orderId" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", r.PathValue("orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrder(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelOrder operation middleware
func (siw *ServerInterfaceWrapper) CancelOrder(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orderId" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", r.PathValue("orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelOrder(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPriceHistory operation middleware
func (siw *ServerInterfaceWrapper) ListPriceHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPriceHistoryParams

	// ------------- Required query parameter "assetCode" -------------

	if paramValue := r.URL.Query().Get("assetCode"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "assetCode"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "assetCode", r.URL.Query(), &params.AssetCode)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "assetCode", Err: err})
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPriceHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLatestPrices operation middleware
func (siw *ServerInterfaceWrapper) GetLatestPrices(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestPricesParams

	// ------------- Optional query parameter "assetCode" -------------

	err = runtime.BindQueryParameter("form", true, false, "assetCode", r.URL.Query(), &params.AssetCode)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "assetCode", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLatestPrices(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystemSummary operation middleware
func (siw *ServerInterfaceWrapper) GetSystemSummary(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemSummary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/balances/latest", wrapper.GetLatestBalances)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/executions", wrapper.ListExecutions)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/job-runs", wrapper.ListJobRuns)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/job-runs/daily-trade", wrapper.TriggerDailyTradeJob)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/job-runs/order-reconcile", wrapper.TriggerOrderReconcileJob)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/job-runs/price-fetch", wrapper.TriggerPriceFetchJob)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/orders", wrapper.ListOrders)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/orders", wrapper.CreateOrder)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/orders/{orderId}", wrapper.GetOrder)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/orders/{orderId}/cancel", wrapper.CancelOrder)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/prices/history", wrapper.ListPriceHistory)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/prices/latest", wrapper.GetLatestPrices)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/system/summary", wrapper.GetSystemSummary)
	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealth)

	return m
}

type NotFoundJSONResponse ErrorResponse

type UnauthorizedResponseHeaders struct {
	WWWAuthenticate string
}
type UnauthorizedTextResponse struct {
	Body string

	Headers UnauthorizedResponseHeaders
}

type GetLatestBalancesRequestObject struct {
	Params GetLatestBalancesParams
}

type GetLatestBalancesResponseObject interface {
	VisitGetLatestBalancesResponse(w http.ResponseWriter) error
}

type GetLatestBalances200JSONResponse LatestBalancesResponse

func (response GetLatestBalances200JSONResponse) VisitGetLatestBalancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLatestBalances401TextResponse struct{ UnauthorizedTextResponse }

func (response GetLatestBalances401TextResponse) VisitGetLatestBalancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	_, err := w.Write([]byte(response.Body))
	return err
}

type ListExecutionsRequestObject struct {
	Params ListExecutionsParams
}

type ListExecutionsResponseObject interface {
	VisitListExecutionsResponse(w http.ResponseWriter) error
}

type ListExecutions200JSONResponse ExecutionListResponse

func (response ListExecutions200JSONResponse) VisitListExecutionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListExecutions401TextResponse struct{ UnauthorizedTextResponse }

func (response ListExecutions401TextResponse) VisitListExecutionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	_, err := w.Write([]byte(response.Body))
	return err
}

type ListJobRunsRequestObject struct {
	Params ListJobRunsParams
}

type ListJobRunsResponseObject interface {
	VisitListJobRunsResponse(w http.ResponseWriter) error
}

type ListJobRuns200JSONResponse JobRunListResponse

func (response ListJobRuns200JSONResponse) VisitListJobRunsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListJobRuns401TextResponse struct{ UnauthorizedTextResponse }

func (response ListJobRuns401TextResponse) VisitListJobRunsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	_, err := w.Write([]byte(response.Body))
	return err
}

type TriggerDailyTradeJobRequestObject struct {
	Body *TriggerDailyTradeJobJSONRequestBody
}

type TriggerDailyTradeJobResponseObject interface {
	VisitTriggerDailyTradeJobResponse(w http.ResponseWriter) error
}

type TriggerDailyTradeJob202JSONResponse TriggerJobResponse

func (response TriggerDailyTradeJob202JSONResponse) VisitTriggerDailyTradeJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type TriggerDailyTradeJob401TextResponse struct{ UnauthorizedTextResponse }

func (response TriggerDailyTradeJob401TextResponse) VisitTriggerDailyTradeJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	_, err := w.Write([]byte(response.Body))
	return err
}

type TriggerOrderReconcileJobRequestObject struct {
	Body *TriggerOrderReconcileJobJSONRequestBody
}

type TriggerOrderReconcileJobResponseObject interface {
	VisitTriggerOrderReconcileJobResponse(w http.ResponseWriter) error
}

type TriggerOrderReconcileJob202JSONResponse TriggerJobResponse

func (response TriggerOrderReconcileJob202JSONResponse) VisitTriggerOrderReconcileJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type TriggerOrderReconcileJob401TextResponse struct{ UnauthorizedTextResponse }

func (response TriggerOrderReconcileJob401TextResponse) VisitTriggerOrderReconcileJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	_, err := w.Write([]byte(response.Body))
	return err
}

type TriggerPriceFetchJobRequestObject struct {
	Body *TriggerPriceFetchJobJSONRequestBody
}

type TriggerPriceFetchJobResponseObject interface {
	VisitTriggerPriceFetchJobResponse(w http.ResponseWriter) error
}

type TriggerPriceFetchJob202JSONResponse TriggerJobResponse

func (response TriggerPriceFetchJob202JSONResponse) VisitTriggerPriceFetchJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type TriggerPriceFetchJob401TextResponse struct{ UnauthorizedTextResponse }

func (response TriggerPriceFetchJob401TextResponse) VisitTriggerPriceFetchJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	_, err := w.Write([]byte(response.Body))
	return err
}

type ListOrdersRequestObject struct {
	Params ListOrdersParams
}

type ListOrdersResponseObject interface {
	VisitListOrdersResponse(w http.ResponseWriter) error
}

type ListOrders200JSONResponse OrderListResponse

func (response ListOrders200JSONResponse) VisitListOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListOrders401TextResponse struct{ UnauthorizedTextResponse }

func (response ListOrders401TextResponse) VisitListOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	_, err := w.Write([]byte(response.Body))
	return err
}

type CreateOrderRequestObject struct {
	Body *CreateOrderJSONRequestBody
}

type CreateOrderResponseObject interface {
	VisitCreateOrderResponse(w http.ResponseWriter) error
}

type CreateOrder201JSONResponse CreateOrderResponse

func (response CreateOrder201JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrder401TextResponse struct{ UnauthorizedTextResponse }

func (response CreateOrder401TextResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	_, err := w.Write([]byte(response.Body))
	return err
}

type GetOrderRequestObject struct {
	OrderId OrderId `json:"orderId"`
}

type GetOrderResponseObject interface {
	VisitGetOrderResponse(w http.ResponseWriter) error
}

type GetOrder200JSONResponse OrderDetailResponse

func (response GetOrder200JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOrder401TextResponse struct{ UnauthorizedTextResponse }

func (response GetOrder401TextResponse) VisitGetOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	_, err := w.Write([]byte(response.Body))
	return err
}

type GetOrder404JSONResponse struct{ NotFoundJSONResponse }

func (response GetOrder404JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CancelOrderRequestObject struct {
	OrderId OrderId `json:"orderId"`
}

type CancelOrderResponseObject interface {
	VisitCancelOrderResponse(w http.ResponseWriter) error
}

type CancelOrder200JSONResponse CancelOrderResponse

func (response CancelOrder200JSONResponse) VisitCancelOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CancelOrder401TextResponse struct{ UnauthorizedTextResponse }

func (response CancelOrder401TextResponse) VisitCancelOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	_, err := w.Write([]byte(response.Body))
	return err
}

type CancelOrder404JSONResponse struct{ NotFoundJSONResponse }

func (response CancelOrder404JSONResponse) VisitCancelOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListPriceHistoryRequestObject struct {
	Params ListPriceHistoryParams
}

type ListPriceHistoryResponseObject interface {
	VisitListPriceHistoryResponse(w http.ResponseWriter) error
}

type ListPriceHistory200JSONResponse PriceHistoryResponse

func (response ListPriceHistory200JSONResponse) VisitListPriceHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListPriceHistory401TextResponse struct{ UnauthorizedTextResponse }

func (response ListPriceHistory401TextResponse) VisitListPriceHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	_, err := w.Write([]byte(response.Body))
	return err
}

type GetLatestPricesRequestObject struct {
	Params GetLatestPricesParams
}

type GetLatestPricesResponseObject interface {
	VisitGetLatestPricesResponse(w http.ResponseWriter) error
}

type GetLatestPrices200JSONResponse LatestPricesResponse

func (response GetLatestPrices200JSONResponse) VisitGetLatestPricesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLatestPrices401TextResponse struct{ UnauthorizedTextResponse }

func (response GetLatestPrices401TextResponse) VisitGetLatestPricesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	_, err := w.Write([]byte(response.Body))
	return err
}

type GetSystemSummaryRequestObject struct {
}

type GetSystemSummaryResponseObject interface {
	VisitGetSystemSummaryResponse(w http.ResponseWriter) error
}

type GetSystemSummary200JSONResponse SystemSummaryResponse

func (response GetSystemSummary200JSONResponse) VisitGetSystemSummaryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSystemSummary401TextResponse struct{ UnauthorizedTextResponse }

func (response GetSystemSummary401TextResponse) VisitGetSystemSummaryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	_, err := w.Write([]byte(response.Body))
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// 最新残高を取得
	// (GET /api/v1/balances/latest)
	GetLatestBalances(ctx context.Context, request GetLatestBalancesRequestObject) (GetLatestBalancesResponseObject, error)
	// 約定履歴を取得
	// (GET /api/v1/executions)
	ListExecutions(ctx context.Context, request ListExecutionsRequestObject) (ListExecutionsResponseObject, error)
	// ジョブ実行履歴を取得
	// (GET /api/v1/job-runs)
	ListJobRuns(ctx context.Context, request ListJobRunsRequestObject) (ListJobRunsResponseObject, error)
	// 日次売買ジョブを手動起動
	// (POST /api/v1/job-runs/daily-trade)
	TriggerDailyTradeJob(ctx context.Context, request TriggerDailyTradeJobRequestObject) (TriggerDailyTradeJobResponseObject, error)
	// 注文同期ジョブを手動起動
	// (POST /api/v1/job-runs/order-reconcile)
	TriggerOrderReconcileJob(ctx context.Context, request TriggerOrderReconcileJobRequestObject) (TriggerOrderReconcileJobResponseObject, error)
	// 価格取得ジョブを手動起動
	// (POST /api/v1/job-runs/price-fetch)
	TriggerPriceFetchJob(ctx context.Context, request TriggerPriceFetchJobRequestObject) (TriggerPriceFetchJobResponseObject, error)
	// 注文一覧を取得
	// (GET /api/v1/orders)
	ListOrders(ctx context.Context, request ListOrdersRequestObject) (ListOrdersResponseObject, error)
	// 注文を作成
	// (POST /api/v1/orders)
	CreateOrder(ctx context.Context, request CreateOrderRequestObject) (CreateOrderResponseObject, error)
	// 注文詳細を取得
	// (GET /api/v1/orders/{orderId})
	GetOrder(ctx context.Context, request GetOrderRequestObject) (GetOrderResponseObject, error)
	// 注文を取消
	// (POST /api/v1/orders/{orderId}/cancel)
	CancelOrder(ctx context.Context, request CancelOrderRequestObject) (CancelOrderResponseObject, error)
	// 価格履歴を取得
	// (GET /api/v1/prices/history)
	ListPriceHistory(ctx context.Context, request ListPriceHistoryRequestObject) (ListPriceHistoryResponseObject, error)
	// 最新価格を取得
	// (GET /api/v1/prices/latest)
	GetLatestPrices(ctx context.Context, request GetLatestPricesRequestObject) (GetLatestPricesResponseObject, error)
	// ダッシュボード向けのサマリーを取得
	// (GET /api/v1/system/summary)
	GetSystemSummary(ctx context.Context, request GetSystemSummaryRequestObject) (GetSystemSummaryResponseObject, error)
	// ヘルスチェック
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetLatestBalances operation middleware
func (sh *strictHandler) GetLatestBalances(w http.ResponseWriter, r *http.Request, params GetLatestBalancesParams) {
	var request GetLatestBalancesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLatestBalances(ctx, request.(GetLatestBalancesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLatestBalances")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLatestBalancesResponseObject); ok {
		if err := validResponse.VisitGetLatestBalancesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListExecutions operation middleware
func (sh *strictHandler) ListExecutions(w http.ResponseWriter, r *http.Request, params ListExecutionsParams) {
	var request ListExecutionsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListExecutions(ctx, request.(ListExecutionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListExecutions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListExecutionsResponseObject); ok {
		if err := validResponse.VisitListExecutionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListJobRuns operation middleware
func (sh *strictHandler) ListJobRuns(w http.ResponseWriter, r *http.Request, params ListJobRunsParams) {
	var request ListJobRunsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListJobRuns(ctx, request.(ListJobRunsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListJobRuns")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListJobRunsResponseObject); ok {
		if err := validResponse.VisitListJobRunsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerDailyTradeJob operation middleware
func (sh *strictHandler) TriggerDailyTradeJob(w http.ResponseWriter, r *http.Request) {
	var request TriggerDailyTradeJobRequestObject

	var body TriggerDailyTradeJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerDailyTradeJob(ctx, request.(TriggerDailyTradeJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerDailyTradeJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerDailyTradeJobResponseObject); ok {
		if err := validResponse.VisitTriggerDailyTradeJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerOrderReconcileJob operation middleware
func (sh *strictHandler) TriggerOrderReconcileJob(w http.ResponseWriter, r *http.Request) {
	var request TriggerOrderReconcileJobRequestObject

	var body TriggerOrderReconcileJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerOrderReconcileJob(ctx, request.(TriggerOrderReconcileJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerOrderReconcileJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerOrderReconcileJobResponseObject); ok {
		if err := validResponse.VisitTriggerOrderReconcileJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerPriceFetchJob operation middleware
func (sh *strictHandler) TriggerPriceFetchJob(w http.ResponseWriter, r *http.Request) {
	var request TriggerPriceFetchJobRequestObject

	var body TriggerPriceFetchJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerPriceFetchJob(ctx, request.(TriggerPriceFetchJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerPriceFetchJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerPriceFetchJobResponseObject); ok {
		if err := validResponse.VisitTriggerPriceFetchJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOrders operation middleware
func (sh *strictHandler) ListOrders(w http.ResponseWriter, r *http.Request, params ListOrdersParams) {
	var request ListOrdersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOrders(ctx, request.(ListOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOrdersResponseObject); ok {
		if err := validResponse.VisitListOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrder operation middleware
func (sh *strictHandler) CreateOrder(w http.ResponseWriter, r *http.Request) {
	var request CreateOrderRequestObject

	var body CreateOrderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrder(ctx, request.(CreateOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrderResponseObject); ok {
		if err := validResponse.VisitCreateOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrder operation middleware
func (sh *strictHandler) GetOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	var request GetOrderRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrder(ctx, request.(GetOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrderResponseObject); ok {
		if err := validResponse.VisitGetOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelOrder operation middleware
func (sh *strictHandler) CancelOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	var request CancelOrderRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelOrder(ctx, request.(CancelOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelOrderResponseObject); ok {
		if err := validResponse.VisitCancelOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPriceHistory operation middleware
func (sh *strictHandler) ListPriceHistory(w http.ResponseWriter, r *http.Request, params ListPriceHistoryParams) {
	var request ListPriceHistoryRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPriceHistory(ctx, request.(ListPriceHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPriceHistory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPriceHistoryResponseObject); ok {
		if err := validResponse.VisitListPriceHistoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLatestPrices operation middleware
func (sh *strictHandler) GetLatestPrices(w http.ResponseWriter, r *http.Request, params GetLatestPricesParams) {
	var request GetLatestPricesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLatestPrices(ctx, request.(GetLatestPricesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLatestPrices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLatestPricesResponseObject); ok {
		if err := validResponse.VisitGetLatestPricesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSystemSummary operation middleware
func (sh *strictHandler) GetSystemSummary(w http.ResponseWriter, r *http.Request) {
	var request GetSystemSummaryRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSystemSummary(ctx, request.(GetSystemSummaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSystemSummary")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSystemSummaryResponseObject); ok {
		if err := validResponse.VisitGetSystemSummaryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbb28TRxr/Ktbcvaqc2AHaQ5H6IgnkCqVNRIJQBSiM15N4wnp3Ozub4qJIrN32aAki",
	"pT3gelFbRIEcLekf2kJVoB9mYif9FqeZ2b/eWXvXcSRelBco3p15nmee3/Nv5pm9BDSzbpkGMqgNxi8B",
	"CxJYRxQR8WvCthGdMquI/8AGGAfvOog0QBEYsI7AOIDBgCKwtRqqQz7y7wQtgnHwt1JIuyTf2qWQ5Opq",
	"MWRwEr3rYIKqWRiRYCwlDhqM8STUoaGh4OGMRbFpQH14C+3mINhOE7M+QdOYLBKzHqO/aJI6pGAcVCFF",
	"IxTXOXvasPhgmxJsLAmqx83KHIXUsdMI2/JtVtGPm5WTjuGR9BjMC65q8sve6xz0xXhO+gSu41SF6OJl",
	"lGwVLUJHp2B8rFwugjq8iOtOHYy/Kn5hQ/4aC5SEDYqWEBGcZkgVkWOhhVmQ1kJWpve2l3kFcGCDvnYI",
	"ZOXYz7ZC1ntkNYfTPdXGOWw3pBbSHqaBRSlyDvNmulNQM79LrHIUbcs0bCREftuk06ZjCOw106DIEOyg",
	"ZelYgxyd0rJtGvxZtgUcJcQkJz0WkmEV2RrBAmowDljrIWs+Z61nrPkbc9d2719l7jfMvcqaHzP3IXM/",
	"AKtFcMqADq2ZBL+PukWj6CItWTrEXUKhi7Bu6SIiObSGDOrJXwisVqmNuHCT0MZaYffhtd3NZ8xda//x",
	"4e59l112mfuCuV8x93v5qtP6sP31j8xd2356rfPoLiiCGoJVLzWcPn16ZCIUAUnnTOXSclnrLmt9x1qP",
	"WfNpDNFwSXIGQVCvv34WaKRhUbNi0rOgWNBqkNiIvn4WnJqfHjl8FqjWyVfqIZTIXsjgznMGTM5PgSI4",
	"Ov8GOJegkEwL0ZnHZ98BxT7zp/hsXZh3YB08qxLTQoRiaY1mGIgSbt7t2kXftXJ6VBjEzkTjixwQSm5W",
	"lpFGheQEQYo8yd91kE2TgsOoWjLm2iKwCNbQcauRtJAq0nAd6gVPfwp9EikKqk6K6Yn3Nu4vTCSYFQEP",
	"GMeMaZNoKJZOwPTEHCgGWE9PvAmK3rPpGf733MybSsQdA8vKKd/SuiCKlRcyUgdq83n0Ra2nvWXSktp0",
	"lJzjETDBU/OsJKGvOrJtuKR618Vak9rwxytluIg0hyv8BLZpuizIHybTF0X1vu40T2AVBeSF4UjmkBDY",
	"SMga4aCS8w0EdVrroawa0i6gqsyBWRJcNCqE4dO80NfOgjwdslQJLAvA3lpdFmOyq9QrKp16HZJGX436",
	"1NOlCwsS32mJYxjS2WxH0xCqimy4CLEu/rAvYMtCVaUXx4VLWhA39qk0kxZv30q16yJYxAa2a/kAxlnz",
	"w3JYm2equWWKrDo6qk6bJJfFETqokebabUTtAHPkIvuLaJ0ZrCEqXIrB+CrybUVE14VFRDW+B6hCrDcW",
	"KHd6UJRBb4EgzTQ0rIsgBA0H6krLOQEpsqlXN9jp7lLxRsRdtjxaHiuLf6CYzY08GxUZtq8XBUxVWpGS",
	"z3JF9JBbKCq7lwtycwa07JrZXz6PuEq6GT9pDaME0URZpuezXk3HyKAzimLNcXBVNQNd1GrQWEKROYox",
	"FibIziPIIhq0fFrEfNGnBitRcsQgbE8jNE1QNPxVTFNHUOROHdpU+vdU/kwnvDFLhJsJBvqz9rB0S4da",
	"Pjn3VubWIea5a2B5cxfCe99WCB/oNvlutymqStsQ0khEj9S7MfDiVpzQVeAeUSuM4JcaW44gCrHeo2pc",
	"8c9EMwU+QfMon5OMesW9l+BFX57U9Uje6mXksWMxwfe3ZEQhZn0uv+nkiCUWbOgmFKNhtYrl0dlsZE3y",
	"VC6hBGrODcmkAwUUA+2lar13jSywy2lDfZOmRzRVJP8U0C91Kg53Dhvp6gKm63QvKJCQUcXG0oLtVOQZ",
	"rGkhgzsWJBRDXW8sSLcM/BP4aXYh2LSDSOYFfuqTR6xc4mh5nipZd+Emj4RVw0Xp8Qa2qUkaL189Eyc0",
	"tLrGog7Zp41FjoQWFrRj5YOHXn3tH4dHxw4EdW0yWZmOd/7Se7eKu/NHJEdElh4QVOk9Vi8PrvZkN6cI",
	"4ArEOqzoaKJuOjL2ZtZTefTAq+kK0k1RJWUlm/1sqVvkLlY9FBiECVsR5ixkTPmyRi3r4AGlZTkGQbap",
	"r6DqLEEr2HTsI7CRnUB3PAy496TcY22nEbqgN4JO1FA80zRsp76HAlTEuYFn772gfA8bVfO9ubyb/h62",
	"F1lRt34UVV03fyV8DZuiugditq33EPbYfD/Dd87Hh3sA5hWJgYtlEDDikzyqIrKCyDyHJXMyeC+0/Nzq",
	"iXpNv8QYka1bfcUQn5gKuoRT4d91Sqs4+JWbk2BI6p6cv8+XRv05AzvY4Lv6HNvyWVmtTWNdV2/N8/Wi",
	"Bt/jqjJ72JdSARWDJZb646qPbQCj61VbDF5aQoTbXlqTiyDotYLjK+x8fLV99d/tra9276ztrH+08/mP",
	"GRpWcRJy8vbT37eff8bcrd1Ht9tX7rUfrSvV1VP23ofyA/QWI31lTUMWVTaSVUf0vfuKIixpDsG0Mcej",
	"hx+QbaxNOLSWVNH5ErRwaWWs9Mr5YuF8Sfzn4NIr5wvM/b6Q0rhunjXOT518Z3Z+ZnJmfmHiyFvH3l44",
	"NXf05NsTbx3lEzcLidezE3Nzp2dOHjlfYM0b28//2Pl8k7n/Yc2rgprfnxbOwnmGyqhRasmeOjYWzeQC",
	"pkTXetKkBeZu7Wzd2Vn/qDAxe0yQbd/9afenJ4WKeLlZOI0qhVPH+MLa62vbTy+z1jprfsNan7DWQ+Y+",
	"2Nl81m5dY+4t0ZnnBsMJcXn/vPwFc28z9/7Of+/u3r/J3E1pnJ3Prm0/32DNG7t31pj7kb8UiqlANhRt",
	"YvYYKIIVRGwpdHl0bLQswoGFDGhhMA4OjpZHD4r9Hq0J0Hxg/GhdkmGcv1qSpTU3ROiHWfBPRONn43Lz",
	"GNwuO6NOMuGQUuodrdVzXfc7DpTLQ7vakXKgr7hG0dm43Ln5Q2fr6p/f3t5+enn3/gOuwkPlsTQWgcyl",
	"2M0P4SV+6ylGlTVvtK/fbL+4xVGES3b8TJ/P81GJ9ziVgJzANj0aDsuLRrS87Tu4++ZThileIbGf0Kr7",
	"xQpkd37+oL31RfvHe51HPw8D0yg9FabR/nEU1WWzMkKcPpiGhVQ+QMOOYJahwUneywCkoj+tuoPVfMpa",
	"D1jrpsy7w4NTSViF67JZSUG0JFqOI7LlyNO4aSvg9VL+ET5WFLvHzQoIioxJs9oYmkqTldFq8h7dgfKB",
	"fWGYjuHuL0941XX91vbvt4cSXW/d63x3RybiAEbWvCETqOSWDUBRvY6EXeJ+IHqXdLzhfwG5VyAfb3Zu",
	"/qu9vtbZ+GpvQIqdxYi8CtAPRHGKO82H/gXgHgHcfnGn8/UzGTIHAjBsrqSmxhk5ZP9LHa+rmnHwy5RK",
	"k10sVaUrnG2INW6Enipv+i2u1WKKO0buPe6TFyruw67Gd8CUOCjplmP7I0FfbJ5vdK6s7/yy3vlyY3gI",
	"ib0xJ6zCJuGKpUveic5qr02hD1o+l/TvE+y/L3TdC0jV+O7/Hu/8/MOAuuaTDvWfFHy3oAJHCtDTfXpA",
	"VJKd2fSMF7nK/nKipbprn4pW+/rNzq9X9uQfw8BMotX59UoftGQjuVST3eyeOS7a9h480wXf32XISt5H",
	"bBlGiu96Xo48p7wdoDAXrywZ2l4xSk/lq/6VAQX6WQ/Y5BXOvVQ5+3+e1nXNNPU0Tapr2KdpkmpW9dui",
	"rViyw9vgafqPNSDBPipR3elUnVxdf9He2GTuljw93vnk185jdyhnHq3LrNVizSesdY+1NljrGWt93F7/",
	"lLmfMneLNX9hrS9Z66H44i2pZqlST8018TnE+70UK7+Y2E+Ndn2ToVDlzJux/gUYP3MurpDbrPUta/7G",
	"Wi5rPhDK+V655DiRWPvjzDnue7I7Kp3WIbrXZRgvlXRTg3rNtOn44fLhsvBTj/yl4MtLyYYHWe9JcEAc",
	"eeaZeeSJl3UiTyKHkJGnYt+1em71/wEAAP//r/w5dSk+AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
