// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BalanceSnapshot struct {
	ID              int64              `json:"id"`
	JobRunID        *int64             `json:"job_run_id"`
	AssetCode       string             `json:"asset_code"`
	AvailableAmount pgtype.Numeric     `json:"available_amount"`
	LockedAmount    pgtype.Numeric     `json:"locked_amount"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type JobRun struct {
	ID           int64              `json:"id"`
	JobType      string             `json:"job_type"`
	Status       string             `json:"status"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	ErrorCode    *string            `json:"error_code"`
	ErrorMessage *string            `json:"error_message"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Order struct {
	ID                  int64              `json:"id"`
	JobRunID            *int64             `json:"job_run_id"`
	ExchangeOrderID     string             `json:"exchange_order_id"`
	ClientOrderID       pgtype.UUID        `json:"client_order_id"`
	AssetCode           string             `json:"asset_code"`
	Side                string             `json:"side"`
	OrderType           string             `json:"order_type"`
	Status              string             `json:"status"`
	PriceJpy            pgtype.Numeric     `json:"price_jpy"`
	OrderedUnits        pgtype.Numeric     `json:"ordered_units"`
	FilledUnits         pgtype.Numeric     `json:"filled_units"`
	RemainingUnits      pgtype.Numeric     `json:"remaining_units"`
	FeeJpy              pgtype.Numeric     `json:"fee_jpy"`
	IsFeeFree           bool               `json:"is_fee_free"`
	PlacedAt            pgtype.Timestamptz `json:"placed_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	CancelledAt         pgtype.Timestamptz `json:"cancelled_at"`
	LastStatusCheckedAt pgtype.Timestamptz `json:"last_status_checked_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type OrderEvent struct {
	ID         int64              `json:"id"`
	OrderID    int64              `json:"order_id"`
	JobRunID   *int64             `json:"job_run_id"`
	EventType  string             `json:"event_type"`
	FromStatus *string            `json:"from_status"`
	ToStatus   *string            `json:"to_status"`
	EventAt    pgtype.Timestamptz `json:"event_at"`
	Payload    []byte             `json:"payload"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type PriceSnapshot struct {
	ID         int64              `json:"id"`
	AssetCode  string             `json:"asset_code"`
	PriceJpy   pgtype.Numeric     `json:"price_jpy"`
	CapturedAt pgtype.Timestamptz `json:"captured_at"`
	Source     string             `json:"source"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type TradeExecution struct {
	ID                  int64              `json:"id"`
	OrderID             int64              `json:"order_id"`
	ExchangeExecutionID string             `json:"exchange_execution_id"`
	ExecutedAt          pgtype.Timestamptz `json:"executed_at"`
	PriceJpy            pgtype.Numeric     `json:"price_jpy"`
	ExecutedUnits       pgtype.Numeric     `json:"executed_units"`
	FeeJpy              pgtype.Numeric     `json:"fee_jpy"`
	IsPartialFill       bool               `json:"is_partial_fill"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}
