// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOpenOrders = `-- name: CountOpenOrders :one
SELECT COUNT(*)::bigint
FROM orders
WHERE status IN ('open', 'partially_filled', 'cancel_requested')
`

func (q *Queries) CountOpenOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenOrders)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnresolvedPreviousDayOrders = `-- name: CountUnresolvedPreviousDayOrders :one
SELECT COUNT(*)::bigint
FROM orders
WHERE status IN ('open', 'partially_filled', 'cancel_requested')
  AND (placed_at AT TIME ZONE 'Asia/Tokyo')::date < (NOW() AT TIME ZONE 'Asia/Tokyo')::date
`

func (q *Queries) CountUnresolvedPreviousDayOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnresolvedPreviousDayOrders)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getOrder = `-- name: GetOrder :one
SELECT
    id,
    exchange_order_id,
    client_order_id,
    asset_code,
    side,
    order_type,
    status,
    price_jpy::text AS price_jpy,
    ordered_units::text AS ordered_units,
    filled_units::text AS filled_units,
    remaining_units::text AS remaining_units,
    fee_jpy::text AS fee_jpy,
    is_fee_free,
    placed_at,
    expires_at,
    cancelled_at,
    last_status_checked_at
FROM orders
WHERE id = $1
`

type GetOrderRow struct {
	ID                  int64              `json:"id"`
	ExchangeOrderID     string             `json:"exchange_order_id"`
	ClientOrderID       pgtype.UUID        `json:"client_order_id"`
	AssetCode           string             `json:"asset_code"`
	Side                string             `json:"side"`
	OrderType           string             `json:"order_type"`
	Status              string             `json:"status"`
	PriceJpy            string             `json:"price_jpy"`
	OrderedUnits        string             `json:"ordered_units"`
	FilledUnits         string             `json:"filled_units"`
	RemainingUnits      string             `json:"remaining_units"`
	FeeJpy              string             `json:"fee_jpy"`
	IsFeeFree           bool               `json:"is_fee_free"`
	PlacedAt            pgtype.Timestamptz `json:"placed_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	CancelledAt         pgtype.Timestamptz `json:"cancelled_at"`
	LastStatusCheckedAt pgtype.Timestamptz `json:"last_status_checked_at"`
}

func (q *Queries) GetOrder(ctx context.Context, id int64) (GetOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i GetOrderRow
	err := row.Scan(
		&i.ID,
		&i.ExchangeOrderID,
		&i.ClientOrderID,
		&i.AssetCode,
		&i.Side,
		&i.OrderType,
		&i.Status,
		&i.PriceJpy,
		&i.OrderedUnits,
		&i.FilledUnits,
		&i.RemainingUnits,
		&i.FeeJpy,
		&i.IsFeeFree,
		&i.PlacedAt,
		&i.ExpiresAt,
		&i.CancelledAt,
		&i.LastStatusCheckedAt,
	)
	return i, err
}

const insertBalanceSnapshot = `-- name: InsertBalanceSnapshot :one
INSERT INTO balance_snapshots (
    job_run_id,
    asset_code,
    available_amount,
    locked_amount,
    captured_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, job_run_id, asset_code, available_amount::text AS available_amount, locked_amount::text AS locked_amount, captured_at
`

type InsertBalanceSnapshotParams struct {
	JobRunID        *int64             `json:"job_run_id"`
	AssetCode       string             `json:"asset_code"`
	AvailableAmount pgtype.Numeric     `json:"available_amount"`
	LockedAmount    pgtype.Numeric     `json:"locked_amount"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
}

type InsertBalanceSnapshotRow struct {
	ID              int64              `json:"id"`
	JobRunID        *int64             `json:"job_run_id"`
	AssetCode       string             `json:"asset_code"`
	AvailableAmount string             `json:"available_amount"`
	LockedAmount    string             `json:"locked_amount"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
}

func (q *Queries) InsertBalanceSnapshot(ctx context.Context, arg InsertBalanceSnapshotParams) (InsertBalanceSnapshotRow, error) {
	row := q.db.QueryRow(ctx, insertBalanceSnapshot,
		arg.JobRunID,
		arg.AssetCode,
		arg.AvailableAmount,
		arg.LockedAmount,
		arg.CapturedAt,
	)
	var i InsertBalanceSnapshotRow
	err := row.Scan(
		&i.ID,
		&i.JobRunID,
		&i.AssetCode,
		&i.AvailableAmount,
		&i.LockedAmount,
		&i.CapturedAt,
	)
	return i, err
}

const insertJobRun = `-- name: InsertJobRun :one
INSERT INTO job_runs (
    job_type,
    status,
    scheduled_for,
    started_at,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, job_type, status, scheduled_for, started_at, finished_at, error_code, error_message
`

type InsertJobRunParams struct {
	JobType      string             `json:"job_type"`
	Status       string             `json:"status"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	Metadata     []byte             `json:"metadata"`
}

type InsertJobRunRow struct {
	ID           int64              `json:"id"`
	JobType      string             `json:"job_type"`
	Status       string             `json:"status"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	ErrorCode    *string            `json:"error_code"`
	ErrorMessage *string            `json:"error_message"`
}

func (q *Queries) InsertJobRun(ctx context.Context, arg InsertJobRunParams) (InsertJobRunRow, error) {
	row := q.db.QueryRow(ctx, insertJobRun,
		arg.JobType,
		arg.Status,
		arg.ScheduledFor,
		arg.StartedAt,
		arg.Metadata,
	)
	var i InsertJobRunRow
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.Status,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}

const insertPriceSnapshot = `-- name: InsertPriceSnapshot :one
INSERT INTO price_snapshots (
    asset_code,
    price_jpy,
    captured_at,
    source
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, asset_code, price_jpy::text AS price_jpy, captured_at, source
`

type InsertPriceSnapshotParams struct {
	AssetCode  string             `json:"asset_code"`
	PriceJpy   pgtype.Numeric     `json:"price_jpy"`
	CapturedAt pgtype.Timestamptz `json:"captured_at"`
	Source     string             `json:"source"`
}

type InsertPriceSnapshotRow struct {
	ID         int64              `json:"id"`
	AssetCode  string             `json:"asset_code"`
	PriceJpy   string             `json:"price_jpy"`
	CapturedAt pgtype.Timestamptz `json:"captured_at"`
	Source     string             `json:"source"`
}

func (q *Queries) InsertPriceSnapshot(ctx context.Context, arg InsertPriceSnapshotParams) (InsertPriceSnapshotRow, error) {
	row := q.db.QueryRow(ctx, insertPriceSnapshot,
		arg.AssetCode,
		arg.PriceJpy,
		arg.CapturedAt,
		arg.Source,
	)
	var i InsertPriceSnapshotRow
	err := row.Scan(
		&i.ID,
		&i.AssetCode,
		&i.PriceJpy,
		&i.CapturedAt,
		&i.Source,
	)
	return i, err
}

const listExecutions = `-- name: ListExecutions :many
SELECT
    te.id,
    te.order_id,
    te.exchange_execution_id,
    te.executed_at,
    te.price_jpy::text AS price_jpy,
    te.executed_units::text AS executed_units,
    te.fee_jpy::text AS fee_jpy,
    te.is_partial_fill
FROM trade_executions te
JOIN orders o ON o.id = te.order_id
WHERE ($1::text IS NULL OR o.asset_code = $1::text)
  AND ($2::bigint IS NULL OR te.order_id = $2::bigint)
ORDER BY te.executed_at DESC, te.id DESC
LIMIT $3
`

type ListExecutionsParams struct {
	AssetCode  *string `json:"asset_code"`
	OrderID    *int64  `json:"order_id"`
	LimitCount int32   `json:"limit_count"`
}

type ListExecutionsRow struct {
	ID                  int64              `json:"id"`
	OrderID             int64              `json:"order_id"`
	ExchangeExecutionID string             `json:"exchange_execution_id"`
	ExecutedAt          pgtype.Timestamptz `json:"executed_at"`
	PriceJpy            string             `json:"price_jpy"`
	ExecutedUnits       string             `json:"executed_units"`
	FeeJpy              string             `json:"fee_jpy"`
	IsPartialFill       bool               `json:"is_partial_fill"`
}

func (q *Queries) ListExecutions(ctx context.Context, arg ListExecutionsParams) ([]ListExecutionsRow, error) {
	rows, err := q.db.Query(ctx, listExecutions, arg.AssetCode, arg.OrderID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExecutionsRow{}
	for rows.Next() {
		var i ListExecutionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ExchangeExecutionID,
			&i.ExecutedAt,
			&i.PriceJpy,
			&i.ExecutedUnits,
			&i.FeeJpy,
			&i.IsPartialFill,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobRuns = `-- name: ListJobRuns :many
SELECT
    id,
    job_type,
    status,
    scheduled_for,
    started_at,
    finished_at,
    error_code,
    error_message
FROM job_runs
WHERE ($1::text IS NULL OR job_type = $1::text)
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY started_at DESC, id DESC
LIMIT $3
`

type ListJobRunsParams struct {
	JobType    *string `json:"job_type"`
	Status     *string `json:"status"`
	LimitCount int32   `json:"limit_count"`
}

type ListJobRunsRow struct {
	ID           int64              `json:"id"`
	JobType      string             `json:"job_type"`
	Status       string             `json:"status"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	ErrorCode    *string            `json:"error_code"`
	ErrorMessage *string            `json:"error_message"`
}

func (q *Queries) ListJobRuns(ctx context.Context, arg ListJobRunsParams) ([]ListJobRunsRow, error) {
	rows, err := q.db.Query(ctx, listJobRuns, arg.JobType, arg.Status, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobRunsRow{}
	for rows.Next() {
		var i ListJobRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobType,
			&i.Status,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestBalances = `-- name: ListLatestBalances :many
WITH ranked AS (
    SELECT DISTINCT ON (asset_code)
        asset_code,
        available_amount::text AS available_amount,
        locked_amount::text AS locked_amount,
        captured_at
    FROM balance_snapshots
    ORDER BY asset_code, captured_at DESC
)
SELECT asset_code, available_amount, locked_amount, captured_at
FROM ranked
ORDER BY asset_code
`

type ListLatestBalancesRow struct {
	AssetCode       string             `json:"asset_code"`
	AvailableAmount string             `json:"available_amount"`
	LockedAmount    string             `json:"locked_amount"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
}

func (q *Queries) ListLatestBalances(ctx context.Context) ([]ListLatestBalancesRow, error) {
	rows, err := q.db.Query(ctx, listLatestBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestBalancesRow{}
	for rows.Next() {
		var i ListLatestBalancesRow
		if err := rows.Scan(
			&i.AssetCode,
			&i.AvailableAmount,
			&i.LockedAmount,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestJobRuns = `-- name: ListLatestJobRuns :many
SELECT
    id,
    job_type,
    status,
    scheduled_for,
    started_at,
    finished_at,
    error_code,
    error_message
FROM job_runs
ORDER BY started_at DESC, id DESC
LIMIT $1
`

type ListLatestJobRunsRow struct {
	ID           int64              `json:"id"`
	JobType      string             `json:"job_type"`
	Status       string             `json:"status"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	ErrorCode    *string            `json:"error_code"`
	ErrorMessage *string            `json:"error_message"`
}

func (q *Queries) ListLatestJobRuns(ctx context.Context, limitCount int32) ([]ListLatestJobRunsRow, error) {
	rows, err := q.db.Query(ctx, listLatestJobRuns, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestJobRunsRow{}
	for rows.Next() {
		var i ListLatestJobRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobType,
			&i.Status,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestPrices = `-- name: ListLatestPrices :many
WITH ranked AS (
    SELECT DISTINCT ON (asset_code)
        id,
        asset_code,
        price_jpy::text AS price_jpy,
        captured_at,
        source
    FROM price_snapshots
    WHERE ($1::text IS NULL OR asset_code = $1::text)
    ORDER BY asset_code, captured_at DESC
)
SELECT id, asset_code, price_jpy, captured_at, source
FROM ranked
ORDER BY asset_code
`

type ListLatestPricesRow struct {
	ID         int64              `json:"id"`
	AssetCode  string             `json:"asset_code"`
	PriceJpy   string             `json:"price_jpy"`
	CapturedAt pgtype.Timestamptz `json:"captured_at"`
	Source     string             `json:"source"`
}

func (q *Queries) ListLatestPrices(ctx context.Context, assetCode *string) ([]ListLatestPricesRow, error) {
	rows, err := q.db.Query(ctx, listLatestPrices, assetCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestPricesRow{}
	for rows.Next() {
		var i ListLatestPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetCode,
			&i.PriceJpy,
			&i.CapturedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderEventsByOrderID = `-- name: ListOrderEventsByOrderID :many
SELECT
    id,
    event_type,
    from_status,
    to_status,
    event_at,
    payload
FROM order_events
WHERE order_id = $1
ORDER BY event_at ASC, id ASC
`

type ListOrderEventsByOrderIDRow struct {
	ID         int64              `json:"id"`
	EventType  string             `json:"event_type"`
	FromStatus *string            `json:"from_status"`
	ToStatus   *string            `json:"to_status"`
	EventAt    pgtype.Timestamptz `json:"event_at"`
	Payload    []byte             `json:"payload"`
}

func (q *Queries) ListOrderEventsByOrderID(ctx context.Context, orderID int64) ([]ListOrderEventsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, listOrderEventsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderEventsByOrderIDRow{}
	for rows.Next() {
		var i ListOrderEventsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.FromStatus,
			&i.ToStatus,
			&i.EventAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT
    id,
    exchange_order_id,
    client_order_id,
    asset_code,
    side,
    order_type,
    status,
    price_jpy::text AS price_jpy,
    ordered_units::text AS ordered_units,
    filled_units::text AS filled_units,
    remaining_units::text AS remaining_units,
    fee_jpy::text AS fee_jpy,
    is_fee_free,
    placed_at,
    expires_at,
    cancelled_at,
    last_status_checked_at
FROM orders
WHERE ($1::text IS NULL OR asset_code = $1::text)
  AND ($2::text IS NULL OR side = $2::text)
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY placed_at DESC, id DESC
LIMIT $4
`

type ListOrdersParams struct {
	AssetCode  *string `json:"asset_code"`
	Side       *string `json:"side"`
	Status     *string `json:"status"`
	LimitCount int32   `json:"limit_count"`
}

type ListOrdersRow struct {
	ID                  int64              `json:"id"`
	ExchangeOrderID     string             `json:"exchange_order_id"`
	ClientOrderID       pgtype.UUID        `json:"client_order_id"`
	AssetCode           string             `json:"asset_code"`
	Side                string             `json:"side"`
	OrderType           string             `json:"order_type"`
	Status              string             `json:"status"`
	PriceJpy            string             `json:"price_jpy"`
	OrderedUnits        string             `json:"ordered_units"`
	FilledUnits         string             `json:"filled_units"`
	RemainingUnits      string             `json:"remaining_units"`
	FeeJpy              string             `json:"fee_jpy"`
	IsFeeFree           bool               `json:"is_fee_free"`
	PlacedAt            pgtype.Timestamptz `json:"placed_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	CancelledAt         pgtype.Timestamptz `json:"cancelled_at"`
	LastStatusCheckedAt pgtype.Timestamptz `json:"last_status_checked_at"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.AssetCode,
		arg.Side,
		arg.Status,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersRow{}
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.ExchangeOrderID,
			&i.ClientOrderID,
			&i.AssetCode,
			&i.Side,
			&i.OrderType,
			&i.Status,
			&i.PriceJpy,
			&i.OrderedUnits,
			&i.FilledUnits,
			&i.RemainingUnits,
			&i.FeeJpy,
			&i.IsFeeFree,
			&i.PlacedAt,
			&i.ExpiresAt,
			&i.CancelledAt,
			&i.LastStatusCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceHistory = `-- name: ListPriceHistory :many
SELECT
    id,
    asset_code,
    price_jpy::text AS price_jpy,
    captured_at,
    source
FROM price_snapshots
WHERE asset_code = $1
  AND ($2::timestamptz IS NULL OR captured_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR captured_at <= $3::timestamptz)
ORDER BY captured_at DESC
LIMIT $4
`

type ListPriceHistoryParams struct {
	AssetCode  string             `json:"asset_code"`
	FromAt     pgtype.Timestamptz `json:"from_at"`
	ToAt       pgtype.Timestamptz `json:"to_at"`
	LimitCount int32              `json:"limit_count"`
}

type ListPriceHistoryRow struct {
	ID         int64              `json:"id"`
	AssetCode  string             `json:"asset_code"`
	PriceJpy   string             `json:"price_jpy"`
	CapturedAt pgtype.Timestamptz `json:"captured_at"`
	Source     string             `json:"source"`
}

func (q *Queries) ListPriceHistory(ctx context.Context, arg ListPriceHistoryParams) ([]ListPriceHistoryRow, error) {
	rows, err := q.db.Query(ctx, listPriceHistory,
		arg.AssetCode,
		arg.FromAt,
		arg.ToAt,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPriceHistoryRow{}
	for rows.Next() {
		var i ListPriceHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetCode,
			&i.PriceJpy,
			&i.CapturedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeklyConsumedBuyUnits = `-- name: ListWeeklyConsumedBuyUnits :many
SELECT
    asset_code,
    COALESCE(SUM(ordered_units), 0)::text AS consumed_units
FROM orders
WHERE side = 'buy'
  AND status IN ('open', 'partially_filled', 'filled', 'cancelled', 'expired')
  AND placed_at >= $1
GROUP BY asset_code
ORDER BY asset_code
`

type ListWeeklyConsumedBuyUnitsRow struct {
	AssetCode     string `json:"asset_code"`
	ConsumedUnits string `json:"consumed_units"`
}

func (q *Queries) ListWeeklyConsumedBuyUnits(ctx context.Context, windowStartedAt pgtype.Timestamptz) ([]ListWeeklyConsumedBuyUnitsRow, error) {
	rows, err := q.db.Query(ctx, listWeeklyConsumedBuyUnits, windowStartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWeeklyConsumedBuyUnitsRow{}
	for rows.Next() {
		var i ListWeeklyConsumedBuyUnitsRow
		if err := rows.Scan(&i.AssetCode, &i.ConsumedUnits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobRunFailed = `-- name: MarkJobRunFailed :exec
UPDATE job_runs
SET status = 'failed',
    finished_at = $1,
    error_code = $2,
    error_message = $3
WHERE id = $4
`

type MarkJobRunFailedParams struct {
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	ErrorCode    *string            `json:"error_code"`
	ErrorMessage *string            `json:"error_message"`
	ID           int64              `json:"id"`
}

func (q *Queries) MarkJobRunFailed(ctx context.Context, arg MarkJobRunFailedParams) error {
	_, err := q.db.Exec(ctx, markJobRunFailed,
		arg.FinishedAt,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const markJobRunSucceeded = `-- name: MarkJobRunSucceeded :exec
UPDATE job_runs
SET status = 'succeeded',
    finished_at = $1,
    error_code = NULL,
    error_message = NULL
WHERE id = $2
`

type MarkJobRunSucceededParams struct {
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	ID         int64              `json:"id"`
}

func (q *Queries) MarkJobRunSucceeded(ctx context.Context, arg MarkJobRunSucceededParams) error {
	_, err := q.db.Exec(ctx, markJobRunSucceeded, arg.FinishedAt, arg.ID)
	return err
}
