// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountOpenOrders(ctx context.Context) (int64, error)
	CountUnresolvedPreviousDayOrders(ctx context.Context) (int64, error)
	GetOrder(ctx context.Context, id int64) (GetOrderRow, error)
	InsertBalanceSnapshot(ctx context.Context, arg InsertBalanceSnapshotParams) (InsertBalanceSnapshotRow, error)
	InsertJobRun(ctx context.Context, arg InsertJobRunParams) (InsertJobRunRow, error)
	InsertOrder(ctx context.Context, arg InsertOrderParams) (InsertOrderRow, error)
	InsertOrderEvent(ctx context.Context, arg InsertOrderEventParams) error
	InsertPriceSnapshot(ctx context.Context, arg InsertPriceSnapshotParams) (InsertPriceSnapshotRow, error)
	InsertTradeExecution(ctx context.Context, arg InsertTradeExecutionParams) error
	ListExecutions(ctx context.Context, arg ListExecutionsParams) ([]ListExecutionsRow, error)
	ListJobRuns(ctx context.Context, arg ListJobRunsParams) ([]ListJobRunsRow, error)
	ListLatestBalances(ctx context.Context) ([]ListLatestBalancesRow, error)
	ListLatestJobRuns(ctx context.Context, limitCount int32) ([]ListLatestJobRunsRow, error)
	ListLatestPrices(ctx context.Context, assetCode *string) ([]ListLatestPricesRow, error)
	ListOrderEventsByOrderID(ctx context.Context, orderID int64) ([]ListOrderEventsByOrderIDRow, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error)
	ListPriceHistory(ctx context.Context, arg ListPriceHistoryParams) ([]ListPriceHistoryRow, error)
	ListReconcilableOrders(ctx context.Context, limitCount int32) ([]ListReconcilableOrdersRow, error)
	ListWeeklyConsumedBuyUnits(ctx context.Context, windowStartedAt pgtype.Timestamptz) ([]ListWeeklyConsumedBuyUnitsRow, error)
	MarkJobRunFailed(ctx context.Context, arg MarkJobRunFailedParams) error
	MarkJobRunSucceeded(ctx context.Context, arg MarkJobRunSucceededParams) error
	MarkOrderCancelRequested(ctx context.Context, arg MarkOrderCancelRequestedParams) error
	MarkOrderCancelled(ctx context.Context, arg MarkOrderCancelledParams) error
	UpdateOrderAfterSync(ctx context.Context, arg UpdateOrderAfterSyncParams) error
}

var _ Querier = (*Queries)(nil)
