// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountOpenOrders(ctx context.Context) (int64, error)
	CountUnresolvedPreviousDayOrders(ctx context.Context) (int64, error)
	GetOrder(ctx context.Context, id int64) (GetOrderRow, error)
	InsertJobRun(ctx context.Context, arg InsertJobRunParams) (InsertJobRunRow, error)
	ListExecutions(ctx context.Context, arg ListExecutionsParams) ([]ListExecutionsRow, error)
	ListJobRuns(ctx context.Context, arg ListJobRunsParams) ([]ListJobRunsRow, error)
	ListLatestBalances(ctx context.Context) ([]ListLatestBalancesRow, error)
	ListLatestJobRuns(ctx context.Context, limitCount int32) ([]ListLatestJobRunsRow, error)
	ListLatestPrices(ctx context.Context, assetCode *string) ([]ListLatestPricesRow, error)
	ListOrderEventsByOrderID(ctx context.Context, orderID int64) ([]ListOrderEventsByOrderIDRow, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error)
	ListPriceHistory(ctx context.Context, arg ListPriceHistoryParams) ([]ListPriceHistoryRow, error)
	ListWeeklyConsumedBuyUnits(ctx context.Context, windowStartedAt pgtype.Timestamptz) ([]ListWeeklyConsumedBuyUnitsRow, error)
}

var _ Querier = (*Queries)(nil)
